### ISSUE TITLE
Blackout enabled causes flickering

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-weathersync#48]
Not sure when or what asset i could have conflicting but i dont have vsync or any other possible weather related controlling script in but i recently dropped in a fresh clean copy of qb weathersync and as soon as i try to enable blackout, power only flickers.

**Comment by TotoYmola** [comment]
yes same here

**Comment by nullvariable** [comment]
can you share your full config/steps that seems to be causing this?

**Comment by SlimChances** [comment]
In a server with Gabz MLOS I get thus issue in a server without then I do not. I don't k ow if that's the only difference but....

**Comment by MaDHouSe79** [comment]
> Not sure when or what asset i could have conflicting but i dont have vsync or any other possible weather related controlling script in but i recently dropped in a fresh clean copy of qb weathersync and as soon as i try to enable blackout, power only flickers.


on client.lua there is a Wait(100) at line 58, make this Wait(1) and its gone.

**Comment by Wafflzdev** [comment]
I was not able to reproduce this issue and the /blackout worked as intended when testing. Please provide the following to assist better and make sure you have the latest version of this script installed.

Describe the bug
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Use this item '....' (item's name from shared.lua if applicable)
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Questions (please complete the following information):

When you last updated: [e.g. last week]
Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
Have you renamed qb- to something custom? [e.g. yes/no]
Additional context
Add any other context about the problem here.

**Comment by LightUpFam** [comment]
> > Not sure when or what asset i could have conflicting but i dont have vsync or any other possible weather related controlling script in but i recently dropped in a fresh clean copy of qb weathersync and as soon as i try to enable blackout, power only flickers.
> 
> on client.lua there is a Wait(100) at line 58, make this Wait(1) and its gone.

I updated the wait(100) to wait(1) and it does help ALOT.
however when you move your camera angle you can see some lighting flicking . 
if there anything else i can do to kill all the lights?

**Comment by MaDHouSe79** [comment]
> 

if you are using a graphics mods it could be related to this as well.
same for mlo's there can be a mlo that give you this issues.

**Comment by MaDHouSe79** [comment]
> > > Not sure when or what asset i could have conflicting but i dont have vsync or any other possible weather related controlling script in but i recently dropped in a fresh clean copy of qb weathersync and as soon as i try to enable blackout, power only flickers.
> > 
> > 
> > on client.lua there is a Wait(100) at line 58, make this Wait(1) and its gone.
> 
> I updated the wait(100) to wait(1) and it does help ALOT. however when you move your camera angle you can see some lighting flicking . if there anything else i can do to kill all the lights?


if you are using a graphics mod, it could be related to this as well.
same for mlo's there can be a mlo that give you this issues.
