### ISSUE TITLE
[BUG] bloack feature broken, lights flicker

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-weathersync#59]
using qbcore 1.1.0

when i used the /blackout feature the lighting only flickers and appears to be bugged. 
I do not have any other type of weather/time resource besides qb weathersync

any advise on fixing this?

**Comment by Wafflzdev** [comment]
I was not able to reproduce this issue and the /blackout worked as intended when testing.  Please provide the following to assist better:


**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Use this item '....' (item's name from shared.lua if applicable)
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**
Add any other context about the problem here.

**Comment by Wafflzdev** [comment]
Could not replicate issue

Please re-open later if you are still having issues after updating to the latest files
